# Nombre de la aplicación
spring.application.name=demo

# Configuración de la base de datos H2 (Modo Archivo)
# Esto creará un archivo llamado 'mibasedatos.mv.db' en la carpeta de tu proyecto
spring.datasource.url=jdbc:h2:file:./data/mibasedatos
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 para ver los datos visualmente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actualiza las tablas automáticamente cuando cambies el código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true